### ISSUE TITLE
[Issue]: Deleted vulnerabilities still appear in risk names that used to have them in attack paths

### ISSUE THREAD

**Issue by AlvinAtThales** [ThalesGroup/security-risk-assessment-tool#133]
### Issue Description

When vulnerabilities that are linked to risks are deleted, they still appear in the risk name. This is an issue occurring in previous versions as well.

### Duplicate Steps

Open any ISRA with existing Risks and Vulnerabilities of which some vulnerabilities have to be linked to the Risks. Delete some of those linked vulnerabilities. Navigate back to Risk to check the risk names of those with the vulnerabilities. The vulnerabilities will still appear in the risk names even though they are no longer present in the attack path. 

### Expected Results

Risk Names should be updated and not display the deleted vulnerabilities

### Version Detected

1.0.2

**Comment by ThomasDThales** [comment]
After vulnerabilities that are linked to risks are deleted or invalidated, the risk should become invalid and still display the vulnerabilities but with border color as red? So the risks are not modified without letting the user know, and he has to update the attack path manually.

**Comment by CarlatThales** [comment]
Currently, if we delete the vulnerability from the vulnerabilities tab and we actually automatically remove it from the attack path on the risk tab, then the risk is considered valid today. So a workaround is to keep the vulnerability in the attack path, and check if it exists, and if it does not exist, simply make the risk red.

**Comment by Alvin-JohnPagente** [comment]
After the fix the behavior is now:
- Delete a vulnerability that is referenced in a risk
- Check the affected risk, it is now in Red but the vulnerability is still in the risk name column
- The deleted vulnerability is also in the dropdown
- In the attack path, choose a new vulnerability
- The risk turns black and the vulnerability is in the risk name column
- Go to the attack path drop down and notice that the deleted risks disappears
