### ISSUE TITLE
[Issue]: Clarify meaning on Revision number of Report tab

### ISSUE THREAD

**Issue by ferrarianthony** [ThalesGroup/security-risk-assessment-tool#170]
### Issue Description

a revision number is reported within the report tab while it has no defined meaning (no "revision" on welcome tab).

In fact, it currently corresponds to the `iteration` property of the schema, which is counting the number of file modification (savings).

This `iteration` property is not synchronized with the Iterations History table (`ISRATracking.length`) which is edited manually ==>it is very likely that the history table will contain lower entries than the `iteration` property value which is counting every single updates.

It might be confusing for traceability within generated/printed reports.

### Duplicate Steps

Any

### Expected Results

Several options can be discussed among printing last iteration entry or combining the two information such as `Iteration/Revision: 2 (#16)`

### Version Detected

1.1.0 (Default)

**Comment by CarlatThales** [comment]
Confirmation: When iteration is updated in Project Context OR file is saved after a modification the iteration counter is updated which should not be the case, it should only depend on the iteration cound.

**Comment by CarlatThales** [comment]
Since we have iteration value which is incremented at each save in the JSON file, i propose we do not display this at all. Instead, we rename in the Welcome page -> Iterations history by revision history and also in the iteration column, rename it revision. The ISRA Report page is kept as is.
