### ISSUE TITLE
[Issue]: Opening a .sra file with help of file association (double click) does not open the file correctly

### ISSUE THREAD

**Issue by SebAtThales** [ThalesGroup/security-risk-assessment-tool#176]
### Issue Description

On windows, when double clicking on a .sra file, the sratool is creating a new empty risk assessment instead of displaying the .sra content.

### Duplicate Steps

Use sratool 1.1.0 installer to get file association.
Get a valid and non empty risk assessment file, named with .sra extension.
Double click on the .sra file, sratool is launched but with an empty risk assessment.

### Expected Results

sratool should open and display .sra file content.

### Version Detected

1.1.0 (Default)

**Comment by CarlatThales** [comment]
Tested ok.
