### ISSUE TITLE
[Issue]: Existing risks are still valid even when selected business asset do not exist or are deleted

### ISSUE THREAD

**Issue by AlvinAtThales** [ThalesGroup/security-risk-assessment-tool#177]
### Issue Description

After deleting a business asset, any risk that contains the business asset would remain valid but the options will be blank since the reference is missing. 

### Duplicate Steps

Delete a business asset that is linked to a Risk
Check the Risk and it will still remain valid, the selection for Business Asset and Supporting Asset will be blank 

### Expected Results

The selection should reset to "Select..." and risks should become invalid 

### Version Detected

1.1.0 (Default)

**Comment by ThomasDThales** [comment]
Ideas for expected result regarding the fact that something will invalidate the risk:
 - Should we keep displaying the previous Business Asset and Supporting Asset but with border color of the select input as red?
 - Reset to "Select..." ?
For every case, should we set border color of inputs as red when required and empty or invalid?
