### ISSUE TITLE
[Issue]: The text in "Risk Mitigation" security control description may disappear

### ISSUE THREAD

**Issue by kokchaiang** [ThalesGroup/security-risk-assessment-tool#191]
### Issue Description

The text in "Risk Mitigation" I have filled is gone on some of the risks.

### Duplicate Steps

Randomly.

### Expected Results

The text in "Risk Mitigation" is saved.

### Version Detected

1.1.0 (Default)

**Comment by CarlatThales** [comment]
After analysis, the actual text is still there, but it simply does not appear anymore. 

Current workaround is to close and reopen the SRA form. 
Requested to check if switching tabs and going back to same tab also works as workaround, pending confirmation.

**Comment by Alvin-JohnPagente** [comment]
To reproduce the issue:

- Go to Risks tab
- Type some text in Risk Mitigation/Security control description
- Click on the Risks tab quickly multiple times
- The text disappears
