### ISSUE TITLE
[Issue]: Revision value is reset to 1

### ISSUE THREAD

**Issue by kokchaiang** [ThalesGroup/security-risk-assessment-tool#192]
### Issue Description

I am working on a document and keep saving but the revision in the ISRA report somehow reset to 1.

### Expected Results

The revision number is either increased by 1 for each save operation or can manually set the value to pretend the number growing too fast.

### Version Detected

1.1.0 (Default)

**Comment by CarlatThales** [comment]
Duplicate of #170
