### ISSUE TITLE
[Issue]: The ISRA report page doesn't display the Mitigated Score

### ISSUE THREAD

**Issue by ThomasDThales** [ThalesGroup/security-risk-assessment-tool#202]
### Issue Description

![image](https://github.com/ThalesGroup/security-risk-assessment-tool/assets/164328304/37a51391-9c68-45fe-8079-6a4bb467c781)

Only Inherent and Residual Scores are displayed

### Duplicate Steps

Execute the tool
Fill with Data
Navigate to ISRA Report Panel

### Expected Results

See a "Mitigated Score" column in the report containing the right data

### Version Detected

1.1.0 (Default)

**Comment by Alvin-JohnPagente** [comment]
The Mitigated Score column have been inserted as shown
![image](https://github.com/ThalesGroup/security-risk-assessment-tool/assets/144093856/2c3d6336-17a8-4aaf-8fed-82b36f7ada06)
