### ISSUE TITLE
[Issue]: Quickly adding mitigation ”Security control Description” makes the display of the textarea inputs weird

### ISSUE THREAD

**Issue by ThomasDThales** [ThalesGroup/security-risk-assessment-tool#207]
### Issue Description

![image](https://github.com/ThalesGroup/security-risk-assessment-tool/assets/164328304/7d55c37b-9ab7-45e7-9b7e-1df94dde26c0)

The textarea inputs seem not entirely loaded

### Duplicate Steps

Go to "Risks" > "Risk Mitigation"
Click frantically on the "Add" button

### Expected Results

Usual display of the inputs

### Version Detected

1.1.0 (Default)

**Comment by Alvin-JohnPagente** [comment]
Text entered in the text field will disappear if the Risk tabbed is clicked fast
