### ISSUE TITLE
[Issue]: Adding rows doesn't update the ids

### ISSUE THREAD

**Issue by ThomasDThales** [ThalesGroup/security-risk-assessment-tool#212]
### Issue Description

![image](https://github.com/ThalesGroup/security-risk-assessment-tool/assets/164328304/d9c592ce-2171-45b9-8776-762dcb351131)

![image](https://github.com/ThalesGroup/security-risk-assessment-tool/assets/164328304/9629bab0-d96d-437d-86b9-398e3dfe4d65)

Adding an row to table doesn't always display a following id.
Especially when the previous row has been deleted before.

### Duplicate Steps

Go to "Business Assets" Panel
Add a row to "List of Business Assets"
Delete it
Add a new row to "List of Business Assets"

### Expected Results

Either:
- The id should not be displayed
- The id should be updated (so the corresponding one in the other objects...)

### Version Detected

1.1.0 (Default)

**Comment by CarlatThales** [comment]
This is not a real issue, normally each ID must be unique in the JSON file by design, It could be possible to create/delete/create when not saving and having the same ID, but this complicated to do.
