### ISSUE TITLE
[Issue]: It is possible to select an invalid Supporting Asset in the Vulnerabilities Panel

### ISSUE THREAD

**Issue by ThomasDThales** [ThalesGroup/security-risk-assessment-tool#224]
### Issue Description

![image](https://github.com/ThalesGroup/security-risk-assessment-tool/assets/164328304/65b00082-5a19-4b12-bf9b-a905ca723f37)

![image](https://github.com/ThalesGroup/security-risk-assessment-tool/assets/164328304/b91945f2-db32-4b85-93a6-846fb60d3e9c)

### Duplicate Steps

Create a Supporting asset
Don't associate any Business Asset
Go to the Vulnerabilities Panel
See the invalid Supporting asset selectable in the list

### Expected Results

Display the invalid Supporting assets as red
Invalid every vulnerability containing invalid supporting assets

### Version Detected

1.1.0 (Default)

**Comment by ThomasDThales** [comment]
Possible Solutions: 
 1) Don't display invalid Supporting asset in the list (Same as Supporting asset & Business asset select input for Risk)
 2) Display invalid Supporting asset in red + prevent from being selected in the list
 3) Invalid the Vulnerability + Display an error for the Vulnerability that contains invalid Supporting Assets (Compatible with 1 & 2)

**Comment by Alvin-JohnPagente** [comment]
Is the supporting asset supposed to be red and not selectable?

In the Supporting Assets tab, should the invalid item be red like other tabs?
![image](https://github.com/ThalesGroup/security-risk-assessment-tool/assets/144093856/7f935954-f429-4831-94cc-5138686207e0)

**Comment by ThomasDThales** [comment]
> Is the supporting asset supposed to be red and not selectable?
> 
> In the Supporting Assets tab, should the invalid item be red like other tabs? ![image](https://private-user-images.githubusercontent.com/144093856/322421295-7f935954-f429-4831-94cc-5138686207e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzIwNzcsIm5iZiI6MTcxMzQzMTc3NywicGF0aCI6Ii8xNDQwOTM4NTYvMzIyNDIxMjk1LTdmOTM1OTU0LWY0MjktNDgzMS05NGNjLTUxMzg2ODYyMDdlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwOTE2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTIyODA2ODU5Njk0Nzg3MmM3NjcwYTZhYTlkMDhjNTk3YmY3OTBiYTRhYWI2ZDQwYjk4ZWViNjE5YzdmYTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eHW2zu0NOgB6DYMPw9bda86WUrLCtPuVQYLGLI4M82I)

see https://github.com/ThalesGroup/security-risk-assessment-tool/pull/235 for this matter

**Comment by ThomasDThales** [comment]
> > Expected Result: Invalid the Vulnerability + Display invalid Supporting asset in red
> 
> The expected result in the bug description is different....

Updated
