### ISSUE TITLE
[Issue]: In a risk, we're allowed to select a supporting asset without business asset (but SA disappears if a BA is selected)

### ISSUE THREAD

**Issue by ThomasDThales** [ThalesGroup/security-risk-assessment-tool#234]
### Issue Description

![image](https://github.com/ThalesGroup/security-risk-assessment-tool/assets/164328304/7327d53b-9764-4013-8fa0-ef9cf01c81ee)
![image](https://github.com/ThalesGroup/security-risk-assessment-tool/assets/164328304/81a634c8-5181-4888-b956-98c9b462b7e2)

### Duplicate Steps

Go to  "Risks" Panel
Create a new risk
Select a Supporting Asset
Select a Business Asset
See the Supporting Asset has disappeared

### Expected Results

Solution
 Not possible to select a supporting asset without business asset selected
 Maybe display a tip to select business asset before

### Version Detected

1.1.0 (Default)

**Comment by ThomasDThales** [comment]
Fixed with #235 
Now we check for every supporting asset if it contains the same business asset as the risk

**Comment by CarlatThales** [comment]
Resolved.
