### ISSUE TITLE
After drag to resize the Name text box, the value inside the text box cannot be read

### ISSUE THREAD

**Issue by ssyap78** [ThalesGroup/security-risk-assessment-tool#88]
[](url)Steps to reproduce:

1. Navigate to Business Assets
2. Enter the Name text field with text more than 1 line
3. Drag the Name text field to resize it bigger
4. The text becomes 1 line, but cannot be fully read

![image](https://github.com/ThalesGroup/security-risk-assessment-tool/assets/120545203/fe7603e6-5c58-4b35-b9b1-cca4d3252b5a)

**Comment by ThomasDThales** [comment]
Updated to display:
![image](https://github.com/ThalesGroup/security-risk-assessment-tool/assets/164328304/93c0507c-1cfa-4f04-9548-ca93a47711f7)

Text wrapped + prevent from manual resizing

Textearea automatically fit the cell
![image](https://github.com/ThalesGroup/security-risk-assessment-tool/assets/164328304/b5426ffa-e09f-4a5e-9328-7a37ccf2088b)
