### ISSUE TITLE
Validation tooltip is triggered even when CVE Score is valid

### ISSUE THREAD

**Issue by AlvinAtThales** [ThalesGroup/security-risk-assessment-tool#97]
Version: 1.0.1

Issue description:
When the CVE score is a floating integer within 9 decimal places, a validation tooltip stating "Please enter a valid value. The two nearest valid values are..." will be shown on hover. 

Duplicate Steps:
Go to CVE Official CVSS Score under Vulnerabilities Tab and input a value that has a decimal place between 0 to 10. Hover on the text box, a validation tooltip will be displayed.

Expected Result:
There should not be a validation tooltip as the value is valid.

Attachments:
![image](https://github.com/ThalesGroup/security-risk-assessment-tool/assets/133637296/e86dfee0-a421-4216-9435-8209e09bcf91)

**Comment by CarlatThales** [comment]
After review of the fix, this would require a step of 0.000000001 which would render the control unusable. The decision has been made to have a step of 0.1. This would require a change in JSON validation where the value will be rounded to one decimal digit and and the input will only allow this.
